version: "3.8"

services:
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: drive-report-api
    environment:
      - NODE_ENV=production
      - PORT=5000
      - TZ=Asia/Bangkok
    volumes:
      - api_data:/usr/src/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "fetch('http://localhost:5000/api/health').then(r=>process.exit(r.ok?0:1)).catch(()=>process.exit(1))"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: drive-report-web
    depends_on:
      api:
        condition: service_healthy
    ports:
      - "8080:80"
    restart: unless-stopped

networks:
  default:
    name: drive-report-net

volumes:
  api_data:

